# Github actions workflow file

name: Actions Test

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Checking out the code bro!"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files in this code
        run: ls frontend
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
      - name: Build and Push Docker
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jnaeder324/dunzo-frontend:latest
